### ISSUE TITLE
Controller sends input to PS4 even while DS

### ISSUE THREAD

**Issue by jhogins** [Jays2Kings/DS4Windows#31]
So, during my first usage of Ds4Windows I had my PS4 running and its display off. By the end of the night of playing, I had made over $90 of purchases on PSN. Trying to get a refund :(
Repro:
1. Start Ds4Windows
2. Start Ps4 console nearby
3. Open controller properties to see raw input
4. Move left stick
5. Observe feedback in controller properties and on PS4 UI

Expected: The PS4 should not receive input from the DS4 while Ds4Windows is running
Actual: Both receive input

**Comment by DerekTurtleRoe** [comment]
@jhogins Has your issue been fixed in the newer versions?

**Comment by jhogins** [comment]
Nope, just tried on the latest version and this is still an issue.

**Comment by DerekTurtleRoe** [comment]
You should have the DS4 paired with only one of them at a time if you are using Bluetooth. I also recommend turning your PS4 off or putting it into rest mode while using the DS4 on the PC.

The only thing that is weird is I don't think the controller allows you to pair to more than one device at a time. So in theory, this would be impossible without another controller.

You should check to make sure there are no other Bluetooth controllers in the area around where you are using your PS4.

I have never heard of anything like this before, so I recommend checking for the latest system software and turning your PS4 off when you are using the DS4 on PC to avoid issues.

I suppose you could also use USB instead of Bluetooth, that would also unpair the device from the PS4 when it was in use. That's how it is suppose to work, anyway.

I don't think Sony is going to give you a refund, by the way. They really like money. :disappointed:

**Comment by jhogins** [comment]
They actually did give me a refund, in the form of account credit :D But
let me clarify my repro. I am actually using USB. I would indeed expect
pairing bluetooth to solve the problem, but USB seems to be special.

Thanks for looking into it.

On Mon, Apr 4, 2016 at 2:35 PM, vgturtle127 notifications@github.com
wrote:

> You should have the DS4 paired with only one of them at a time if you are
> using Bluetooth. I also recommend turning your PS4 off or putting it into
> rest mode while using the DS4 on the PC.
> 
> The only thing that is weird is I don't think the controller allows you to
> pair to more than one device at a time. So in theory, this would be
> impossible without another controller.
> 
> You should check to make sure there are no other Bluetooth controllers in
> the area around where you are using your PS4.
> 
> I have never heard of anything like this before, so I recommend checking
> for the latest system software and turning your PS4 off when you are using
> the DS4 on PC to avoid issues.
> 
> I suppose you could also use USB instead of Bluetooth, that would also
> unpair the device from the PS4 when it was in use. That's how it is suppose
> to work, anyway.
> 
> I don't think Sony is going to give you a refund, by the way. They really
> like money. [image: :disappointed:]
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Jays2Kings/DS4Windows/issues/31#issuecomment-205507372

## 

Jon Hogins

**Comment by DerekTurtleRoe** [comment]
@jhogins Huh, didn't expect that from Sony. Maybe they are more forgiving than I thought.

Is the controller on and paired to the PS4 when you plug it into your PC? If so, you should turn it off from the PS4 menu before you play. That would solve the problem. I think, anyway.
